@extends('index')
@section('content')
    
@include('partials.header')
@include('partials.programHero')
@include('partials.slider')
@include('partials.curriculam')
@include('partials.quote')
@include('partials.aferGraduation')
@include('partials.meetOurTeamOrganizer')
@include('partials.codingBootcampLocation')
@include('partials.scholarShip')
@include('partials.faq')
@include('partials.getInTouch')
@include('partials.footer')
@endsection